// Generated by CoffeeScript 2.0.1
(function() {
  $(function() {
    return app.initialize();
  });

  window.app = {
    initialize: function() {
      var self;
      this.setNotSideView();
      this.setListSize();
      self = this;
      $(window).on('resize', function() {
        self.setListSize();
        //端末を縦で見るとき
        return self.setNotSideView();
      });
      this.is_submit = true;
      this.page_count = 1;
      this.json_data = [];
      this.evaluate_point = [0, 0, 0, 0];
      this.item = ['cute', 'beautiful', 'durability', 'reproduction'];
      this.getJsonData();
      this.setTitle();
      return this.setBind();
    },
    setNotSideView: function() {
      var w_height;
      w_height = $(window).height();
      if (w_height <= 800) {
        $('.form-head').css('top', '7%');
        $('.form-wrap ul').css('padding-top', '18%');
        return $('.paginate-wrap').css('bottom', '9%');
      } else {
        $('.form-head').css('top', '25%');
        $('.form-wrap ul').css('padding-top', '45%');
        return $('.paginate-wrap').css('bottom', '27%');
      }
    },
    setListSize: function() {
      var set_list_height01, set_list_height02, set_list_height03, set_list_width, set_w_height;
      set_w_height = $(window).height();
      $('.contents-wrap').css('height', set_w_height);
      set_list_width = $('#list01 .data-list').width();
      set_list_height01 = Math.floor(Math.floor($('#list01 .data-list').width()));
      set_list_height02 = Math.floor(Math.floor($('#list02 .data-list').width()));
      set_list_height03 = Math.floor(Math.floor($('#list03 .data-list').width()) * 1.13);
      $('#list01 .data-list').css('height', set_list_height01);
      $('#list02 .data-list').css('height', set_list_height02);
      return $('#list03 .data-list').css('height', set_list_height03);
    },
    setTitle: function() {
      var page_title;
      page_title = ['髪質改善', '頭皮ケア', 'デザイン'];
      return $('.form-head h1').text(page_title[this.page_count - 1]);
    },
    getJsonData: function() {
      var self;
      self = this;
      return $.getJSON("./assets/js/data.json", function(data) {
        return self.json_data = data;
      });
    },
    setBind: function() {
      $('.data-list').on('click', function() {
        return $(this).toggleClass('active');
      });
      return this.setPageMove();
    },
    setPageMove: function() {
      var self;
      self = this;
      return $('.paginate-wrap .page-move').on('click', function() {
        var val;
        val = $(this).attr('data-page');
        self.page_count = Number(val);
        if (self.page_count !== 4) {
          self.doPageMove(val);
        }
        self.setTitle();
        self.setListSize();
        if (self.page_count === 4 && $(this).hasClass('right-box')) {
          self.setValidate();
          if (self.is_submit) {
            self.setGraphData();
            self.saveGraphData();
            self.saveYourName();
            return location.href = './result.html';
          }
        }
      });
    },
    doPageMove: function(val) {
      var is_page;
      is_page = 'page0' + Number(val);
      this.setPagination();
      return $('body').removeClass().addClass(is_page);
    },
    setPagination: function() {
      var before_page_count, next_page_count;
      before_page_count = this.page_count - 1;
      next_page_count = this.page_count + 1;
      $('.paginate-wrap .left-box').attr('data-page', before_page_count);
      return $('.paginate-wrap .right-box').attr('data-page', next_page_count);
    },
    setGraphData: function() {
      var count, self;
      count = 0;
      self = this;
      return $('.item-list li.active').each(function() {
        var filtered_id, i, set_num;
        i = 0;
        set_num = $(this).attr('data-id');
        filtered_id = $.grep(self.json_data, function(elem, index) {
          return elem.id === Number(set_num);
        });
        return self.evaluate_point.forEach(function(val) {
          var add_val;
          add_val = Number(val + Number(filtered_id[0].point[i]));
          self.evaluate_point[i] = add_val;
          return i++;
        });
      });
    },
    setValidate: function() {
      var error_msg, set_name, set_num;
      this.is_submit = true;
      set_num = 0;
      set_name = $('input[name="name"]').val();
      error_msg = '';
      $('.item-list li.active').each(function() {
        return set_num += $(this).attr('data-id');
      });
      if (set_num === 0) {
        this.is_submit = false;
        error_msg += '一つ以上項目をご選択ください\n';
      }
      if (!set_name) {
        this.is_submit = false;
        error_msg += 'お名前をご入力ください';
      }
      if (!this.is_submit) {
        return alert(error_msg);
      }
    },
    saveYourName: function() {
      var set_your_name;
      set_your_name = $('input[name="name"]').val();
      return localStorage.setItem('yourname', set_your_name);
    },
    saveGraphData: function() {
      var i, j, len, ref, results, val;
      i = 0;
      ref = this.evaluate_point;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        val = ref[j];
        localStorage.setItem(this.item[i], val);
        results.push(i++);
      }
      return results;
    }
  };

}).call(this);
